"""Add CourseIntroSlide table

Revision ID: 0e78455fa4de
Revises: 4574c349fc71
Create Date: 2026-02-08 02:09:17.697053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e78455fa4de'
down_revision: Union[str, Sequence[str], None] = '4574c349fc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_intro_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('slide_id', sa.String(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('audio_file_name', sa.String(), nullable=False),
    sa.Column('narration', sa.JSON(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('reveal_data', sa.JSON(), nullable=False),
    sa.Column('audio_file_url', sa.String(), nullable=True),
    sa.Column('caption', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_intro_slides_course_id'), 'course_intro_slides', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_intro_slides_id'), 'course_intro_slides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_intro_slides_id'), table_name='course_intro_slides')
    op.drop_index(op.f('ix_course_intro_slides_course_id'), table_name='course_intro_slides')
    op.drop_table('course_intro_slides')
    # ### end Alembic commands ###
