"""sync database

Revision ID: 4574c349fc71
Revises: a54d279d2991
Create Date: 2026-02-02 08:56:44.768084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4574c349fc71'
down_revision: Union[str, Sequence[str], None] = 'a54d279d2991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('video_content', sa.JSON(), nullable=True),
    sa.Column('caption', sa.JSON(), nullable=True),
    sa.Column('audio_file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_chapter_id'), 'chapter', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_course_id'), 'chapter', ['course_id'], unique=False)
    op.create_index(op.f('ix_chapter_id'), 'chapter', ['id'], unique=False)
    op.create_table('chapter_content_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('slide_id', sa.String(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('audio_file_name', sa.String(), nullable=False),
    sa.Column('narration', sa.JSON(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('reveal_data', sa.JSON(), nullable=False),
    sa.Column('audio_file_url', sa.String(), nullable=True),
    sa.Column('caption', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_content_slides_chapter_id'), 'chapter_content_slides', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_content_slides_course_id'), 'chapter_content_slides', ['course_id'], unique=False)
    op.create_index(op.f('ix_chapter_content_slides_id'), 'chapter_content_slides', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_input', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('course_layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_chapter_content_slides_id'), table_name='chapter_content_slides')
    op.drop_index(op.f('ix_chapter_content_slides_course_id'), table_name='chapter_content_slides')
    op.drop_index(op.f('ix_chapter_content_slides_chapter_id'), table_name='chapter_content_slides')
    op.drop_table('chapter_content_slides')
    op.drop_index(op.f('ix_chapter_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_course_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_chapter_id'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
